import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import os

# Set page config
st.set_page_config(page_title="Sales Forecasting Dashboard", layout="wide", page_icon="📈")

# Custom CSS for "cool" look
st.markdown("""
<style>
    .metric-card {
        background-color: #f0f2f6;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
    }
    .stPlotlyChart {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
    }
    .explanation-text {
        font-size: 0.9rem;
        color: #555;
        margin-bottom: 15px;
    }
</style>
""", unsafe_allow_html=True)

# Title
st.title("📊 Retail Sales Intelligence Dashboard")
st.markdown("""
**Welcome!** This dashboard visualizes **historical sales performance** and provides **AI-driven future forecasts** for the retail chain.
*   **Explore**: Use the filters on the left to analyze specific Store Categories or individual Stores.
*   **Analyze**: Switch between tabs to see Trends, Comparisons, and Deep Dive Insights.
*   **Plan**: Use the forecasted values to plan inventory and resource allocation for the upcoming months.
""")

# Sidebar Info
st.sidebar.info("""
**ℹ️ About this App**
This dashboard displays pre-computed forecasts generated by a **Prophet** machine learning model. 
It is designed for executives and managers to view trends and make data-driven decisions.
""")

# Load Data
@st.cache_data
def load_data():
    data = {}
    try:
        # Forecasts
        if os.path.exists('outputs/forecast_results.csv'):
            data['forecast'] = pd.read_csv('outputs/forecast_results.csv')
            data['forecast']['ds'] = pd.to_datetime(data['forecast']['ds'])
        
        # Actuals
        if os.path.exists('outputs/actual_sales.csv'):
            data['actuals'] = pd.read_csv('outputs/actual_sales.csv')
            data['actuals']['Date'] = pd.to_datetime(data['actuals']['Date'])
            
        # Monthly Stats
        if os.path.exists('outputs/monthly_stats.csv'):
            data['monthly'] = pd.read_csv('outputs/monthly_stats.csv')
            
        # Yearly Stats
        if os.path.exists('outputs/yearly_stats.csv'):
            data['yearly'] = pd.read_csv('outputs/yearly_stats.csv')
            
        # Top Stores
        if os.path.exists('outputs/top_stores.csv'):
            data['top_stores'] = pd.read_csv('outputs/top_stores.csv')
            
        # Seasonality
        if os.path.exists('outputs/seasonality.csv'):
            data['seasonality'] = pd.read_csv('outputs/seasonality.csv')

        # Heatmap Data
        if os.path.exists('outputs/heatmap_data.csv'):
            data['heatmap'] = pd.read_csv('outputs/heatmap_data.csv')

        # Day of Week Stats
        if os.path.exists('outputs/dayofweek_stats.csv'):
            data['dayofweek'] = pd.read_csv('outputs/dayofweek_stats.csv')
            
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return None

    return data

data = load_data()

if data and 'forecast' in data and 'actuals' in data:
    forecast_df = data['forecast']
    actual_df = data['actuals']
    
    # Sidebar Filters
    st.sidebar.header("Filters")
    
    # StoreType Filter
    store_types = sorted(forecast_df['StoreType'].unique())
    selected_store_type = st.sidebar.selectbox("Select Store Category (StoreType)", ["All"] + list(store_types))

    # Store ID Filter (Optional)
    if selected_store_type != "All":
        available_stores = sorted(actual_df[actual_df['StoreType'] == selected_store_type]['Store'].unique())
    else:
        available_stores = sorted(actual_df['Store'].unique())
    
    selected_store = st.sidebar.selectbox("Select Specific Store (Optional)", ["All"] + list(available_stores))
    
    # Date Range Filter
    min_date = actual_df['Date'].min()
    max_date = forecast_df['ds'].max()
    
    start_date = st.sidebar.date_input("Start Date", min_date)
    end_date = st.sidebar.date_input("End Date", max_date)
    
    # Filter Logic
    filtered_forecast = forecast_df.copy()
    filtered_actual = actual_df.copy()

    if selected_store_type != "All":
        filtered_forecast = filtered_forecast[filtered_forecast['StoreType'] == selected_store_type]
        filtered_actual = filtered_actual[filtered_actual['StoreType'] == selected_store_type]

    if selected_store != "All":
        # For forecast, we might not have store-level forecast in this demo (we did StoreType), 
        # but actuals we do. If user selects a store, we show actuals for that store 
        # and maybe the category forecast as a baseline or hide forecast if not available.
        # For this demo, let's filter actuals and warn about forecast.
        filtered_actual = filtered_actual[filtered_actual['Store'] == selected_store]
        st.warning("Note: Forecasts are generated at the Store Category level. Selecting a specific store shows its Actual Sales vs the Category Forecast Trend.")

    if selected_store == "All" and selected_store_type == "All":
        # Aggregate if 'All' is selected
        filtered_forecast = filtered_forecast.groupby('ds')[['yhat', 'yhat_lower', 'yhat_upper']].sum().reset_index()
        filtered_actual = filtered_actual.groupby('Date')['Sales'].sum().reset_index()
    elif selected_store == "All":
         # Aggregate by StoreType (already filtered)
        filtered_forecast = filtered_forecast.groupby('ds')[['yhat', 'yhat_lower', 'yhat_upper']].sum().reset_index()
        filtered_actual = filtered_actual.groupby('Date')['Sales'].sum().reset_index()

    # Date Mask
    mask_actual = (filtered_actual['Date'] >= pd.to_datetime(start_date)) & (filtered_actual['Date'] <= pd.to_datetime(end_date))
    mask_forecast = (filtered_forecast['ds'] >= pd.to_datetime(start_date)) & (filtered_forecast['ds'] <= pd.to_datetime(end_date))
    
    filtered_actual = filtered_actual.loc[mask_actual]
    filtered_forecast = filtered_forecast.loc[mask_forecast]
    
    # --- KPI Cards ---
    st.subheader("Key Performance Indicators")
    col1, col2, col3, col4 = st.columns(4)
    
    total_sales_actual = filtered_actual['Sales'].sum()
    total_sales_forecast = filtered_forecast['yhat'].sum()
    avg_sales = filtered_actual['Sales'].mean()
    
    with col1:
        st.metric("Total Historical Sales", f"€{total_sales_actual:,.0f}", delta="Actual")
    with col2:
        st.metric("Total Forecasted Sales", f"€{total_sales_forecast:,.0f}", delta="Predicted")
    with col3:
        st.metric("Avg Daily Sales", f"€{avg_sales:,.0f}")
    with col4:
        st.metric("Model Used", "Prophet", delta="Best Performer")

    # --- Decision Insights ---
    st.subheader("💡 Decision Insights")
    i_col1, i_col2, i_col3 = st.columns(3)
    
    # Calculate Insights
    if not filtered_actual.empty:
        # Best Month
        filtered_actual['Month'] = filtered_actual['Date'].dt.month_name()
        best_month = filtered_actual.groupby('Month')['Sales'].sum().idxmax()
        low_month = filtered_actual.groupby('Month')['Sales'].sum().idxmin()
        
        # Top Store (if not single store selected)
        if selected_store == "All":
             # We need original data for this, filtered_actual might be aggregated
             # Let's use the 'top_stores' data if available or re-calculate from loaded data if possible
             # For simplicity, use the static top_stores if available, or just say "N/A"
             top_store_name = data['top_stores'].iloc[0]['Store'] if 'top_stores' in data else "N/A"
        else:
            top_store_name = str(selected_store)

        with i_col1:
             st.info(f"**Best Performing Month:** {best_month}")
        with i_col2:
             st.warning(f"**Lowest Season:** {low_month}")
        with i_col3:
             st.success(f"**Top Performer:** Store {top_store_name}")

    # --- Tabs for different views ---
    tab1, tab2, tab3, tab4 = st.tabs(["📈 Forecast Overview", "📊 Comparisons", "💡 Deep Dive Insights", "🎥 Animated Evolution"])
    
    with tab1:
        st.subheader("Sales Trend: Actual vs Forecast")
        st.markdown("""
        <div class="explanation-text">
        This chart visualizes the historical sales data (blue line) alongside the future predictions generated by our AI model (orange line). 
        The shaded area represents the <b>Confidence Interval</b>, indicating the range within which the true future sales are likely to fall. 
        Use this to identify general trends and potential future performance.
        </div>
        """, unsafe_allow_html=True)
        
        fig = go.Figure()
        
        # Actual Sales
        fig.add_trace(go.Scatter(x=filtered_actual['Date'], y=filtered_actual['Sales'],
                                 mode='lines', name='Actual Sales', line=dict(color='#1f77b4')))
        
        # Forecast
        fig.add_trace(go.Scatter(x=filtered_forecast['ds'], y=filtered_forecast['yhat'],
                                 mode='lines', name='Forecast', line=dict(color='#ff7f0e')))
        
        # Confidence Interval
        fig.add_trace(go.Scatter(
            x=filtered_forecast['ds'].tolist() + filtered_forecast['ds'].tolist()[::-1],
            y=filtered_forecast['yhat_upper'].tolist() + filtered_forecast['yhat_lower'].tolist()[::-1],
            fill='toself',
            fillcolor='rgba(255, 127, 14, 0.2)',
            line=dict(color='rgba(255,255,255,0)'),
            hoverinfo="skip",
            showlegend=False,
            name='Confidence Interval'
        ))
        
        fig.update_layout(xaxis_title="Date", yaxis_title="Sales", hovermode="x unified", template="plotly_white")
        st.plotly_chart(fig, use_container_width=True)
        
    with tab2:
        st.subheader("Monthly & Yearly Comparisons")
        st.markdown("""
        <div class="explanation-text">
        Compare sales performance across different time periods. 
        The <b>Monthly Distribution</b> shows which months contribute most to revenue, helping identify seasonal peaks.
        The <b>Yearly Growth</b> chart highlights the overall business trajectory year-over-year.
        </div>
        """, unsafe_allow_html=True)
        
        col_a, col_b = st.columns(2)
        
        with col_a:
            if 'monthly' in data:
                fig_monthly = px.bar(data['monthly'], x='Date', y='Sales', title="Monthly Sales Distribution",
                                     color='Sales', color_continuous_scale='Viridis')
                st.plotly_chart(fig_monthly, use_container_width=True)
                
        with col_b:
            if 'yearly' in data:
                fig_yearly = px.bar(data['yearly'], x='Year', y='Sales', title="Yearly Sales Growth",
                                    color='Sales', color_continuous_scale='Magma')
                st.plotly_chart(fig_yearly, use_container_width=True)
                
    with tab3:
        st.subheader("Deep Dive Business Insights")
        st.markdown("""
        <div class="explanation-text">
        Explore deeper patterns in your data. 
        <b>Top Stores</b> identifies your highest revenue generators.
        <b>Seasonality</b> reveals recurring monthly patterns.
        <b>Weekly Traffic</b> shows the busiest days of the week.
        <b>Sales Heatmap</b> visualizes intensity of sales across months and days.
        </div>
        """, unsafe_allow_html=True)
        
        col_c, col_d = st.columns(2)
        
        with col_c:
            st.markdown("### Top 10 Performing Stores")
            if 'top_stores' in data:
                fig_top = px.bar(data['top_stores'], x='Sales', y='Store', orientation='h', 
                                 title="Top Stores by Total Sales", color='Sales',
                                 category_orders={"Store": data['top_stores']['Store'].tolist()})
                st.plotly_chart(fig_top, use_container_width=True)
                
        with col_d:
            st.markdown("### Seasonality Analysis")
            if 'seasonality' in data:
                fig_season = px.line(data['seasonality'], x='Month', y='Sales', markers=True,
                                     title="Average Sales per Month (Seasonality)",
                                     line_shape='spline')
                st.plotly_chart(fig_season, use_container_width=True)

        col_e, col_f = st.columns(2)
        
        with col_e:
            st.markdown("### Weekly Sales Distribution")
            if 'dayofweek' in data:
                # Map 0-6 to Mon-Sun
                days = {0:'Mon', 1:'Tue', 2:'Wed', 3:'Thu', 4:'Fri', 5:'Sat', 6:'Sun'}
                data['dayofweek']['DayName'] = data['dayofweek']['DayOfWeek'].map(days)
                fig_pie = px.pie(data['dayofweek'], values='Sales', names='DayName', 
                                 title="Share of Sales by Day of Week",
                                 color_discrete_sequence=px.colors.sequential.RdBu)
                st.plotly_chart(fig_pie, use_container_width=True)

        with col_f:
            st.markdown("### Sales Heatmap (Day vs Month)")
            if 'heatmap' in data:
                days = {0:'Mon', 1:'Tue', 2:'Wed', 3:'Thu', 4:'Fri', 5:'Sat', 6:'Sun'}
                data['heatmap']['DayName'] = data['heatmap']['DayOfWeek'].map(days)
                
                fig_heat = px.density_heatmap(data['heatmap'], x='Month', y='DayName', z='Sales',
                                              title="Sales Intensity Heatmap",
                                              color_continuous_scale='Viridis',
                                              category_orders={"DayName": ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']})
                st.plotly_chart(fig_heat, use_container_width=True)
    
    with tab4:
        st.subheader("Sales Evolution Over Time")
        st.markdown("""
        <div class="explanation-text">
        Watch how sales distribution changes month by month. Press the <b>Play</b> button to see the animation.
        This dynamic view helps visualize the volatility and growth of sales over the entire dataset timeline.
        </div>
        """, unsafe_allow_html=True)
        
        if 'monthly' in data:
            # Prepare data for animation
            anim_data = data['monthly'].copy()
            anim_data['Date'] = pd.to_datetime(anim_data['Date'])
            anim_data['YearMonth'] = anim_data['Date'].dt.strftime('%Y-%m')
            anim_data = anim_data.sort_values('Date')
            
            fig_anim = px.scatter(anim_data, x="Month", y="Sales", animation_frame="YearMonth", 
                                  size="Sales", color="Sales", hover_name="YearMonth",
                                  range_x=[0,13], range_y=[0, anim_data['Sales'].max()*1.1],
                                  title="Monthly Sales Evolution (Press Play)",
                                  color_continuous_scale='Turbo')
            
            fig_anim.update_layout(template="plotly_white")
            st.plotly_chart(fig_anim, use_container_width=True)

else:
    st.warning("Data is loading or not found. Please wait for the analysis notebook to complete.")
